# Generated by Django 5.2 on 2026-08-26 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('order_status', models.CharField(choices=[('PLACED', 'PLACED'), ('CONFIRMED', 'CONFIRMED'), ('SHIPPED', 'SHIPPED'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='PLACED', max_length=50)),
                ('delivery_name', models.CharField(max_length=100)),
                ('delivery_phone', models.CharField(max_length=15)),
                ('delivery_address_line1', models.CharField(max_length=150)),
                ('delivery_address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_pincode', models.CharField(max_length=10)),
                ('delivery_country', models.CharField(default='India', max_length=100)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address_line1', models.CharField(max_length=150)),
                ('address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.order')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productvariant')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.cart')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productvariant')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.user'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.user')),
            ],
            options={
                'db_table': 'wishlist',
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_wishlist')],
            },
        ),
    ]
